/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'bio' : string,
  'linkedin' : string,
  'title' : string,
  'twitter' : string,
  'name' : string,
  'email' : string,
  'github' : string,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'order' : bigint,
  'link' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Review {
  'id' : bigint,
  'role' : string,
  'text' : string,
  'author' : string,
  'avatarUrl' : string,
  'rating' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProject' : ActorMethod<
    [string, string, string, string, string, boolean, bigint],
    bigint
  >,
  'addReview' : ActorMethod<[string, string, string, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getProjectById' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectsByCategory' : ActorMethod<[string], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContactInfo' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, string, string, string, boolean, bigint],
    undefined
  >,
  'updateReview' : ActorMethod<
    [bigint, string, string, string, bigint, string],
    undefined
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];